[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
vaultbot = "4kDczC4oyyY9bhHfzsc2tfCtpTLPeYqagiVhotBmPsX7"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
