[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
vaultbot = "8c8Pf3tJP8DQ94EYVS3j51qRMnVbzNpFpowmV828jeqG"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
